console.log("arsh")
const accountId = 14832
let accountEmail = "arshj347@gmail.com"
var accountPass = "28102910"
accountCity = "Gzb"
let accountstate;
// no value = showing not defined
// accountId = 3 not allowed const change
console.log(accountId);
 accountEmail = "aj@va "
 accountPass = "256"
 accountCity = "jaiopr"
console.log(accountEmail);
console.table([accountId, accountPass, accountCity , accountstate])
/* constant=const only {let(moreee used), 
var(less used beacuse earlier no use over scope bloack and functional scope), 
 ; optionallll*/
